### ISSUE TITLE
Enable download of latest builds for people without GitHub accounts

### ISSUE THREAD

**Issue by yatsuna827** [kwsch/ItemPrinterDeGacha#12]
Downloading artifacts from Github actions [requires signing in to Github](https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts), but this limitation is a hurdle for those who just want to use this application.

**Comment by kwsch** [comment]
There's no setting to toggle allowing access for unregistered users. For a free CI service, it's an acceptable limitation.

I (and anyone else who has contributed, I assume) would be fine with anyone reuploading releases elsewhere, but it might be fine to post another published release once the dust has settled.

**Comment by Xieon** [comment]
A small hurdle. In the long run if you're going to be using any of these programs, having a GitHub account, will be essentially a necessity, and it benefits the end user because they will learn valuable knowledge simply by interacting with the GitHub platform. In the long run users who are participating in user software like this or PkHex benefit from having a Github account, and knowing how to download, build, and compile on their own, in additional to gaining access to the free workflows provided by Github.

**Comment by UnderPsi** [comment]
The artifacts from the Pipelines builds show up as expired now... Would it be possible to issue a final release or re-share the latest pipeline build ? Thanks

**Comment by kwsch** [comment]
Added current build from latest commits as a new release. No changes have been made in the past 3 months, and I don't really expect any further changes (besides maybe translations, which can be managed by others).

https://github.com/kwsch/ItemPrinterDeGacha/releases/tag/1.0.1
